### ISSUE TITLE
Conditions added to event sheet displaying names enclosed in bold markup tags...

### ISSUE THREAD

**Issue by jakemay74** [Armaldio/LoLV2-C3-plugin#1]
...rather than the markup being applied to the text (see attached).

Steps to reproduce:
1. Use the addon manager to add the LoLV2-C3-plugin to C3.
2. Add the LoLV2-C3 object to a new project.
3. Right click on an event sheet and add any LoLV2-C3 condition to the project.

Observed result:
The condition text is displayed within bold markup tags.

Expected result:
The bold markup tags are applied to the text.

![image](https://user-images.githubusercontent.com/7338015/68541538-9486dc80-0398-11ea-9735-eff5be670674.png)

**Comment by Armaldio** [comment]
Just removed the bold tags since C3 doesn't seems to allow markup anymore
